### PR TITLE
Updating to monad-control-0.3, with help from Bas van Dijk.

### PR DESCRIPTION
**Pull request by NathanHowell**

### CODE REVIEW

**Comment by TonyGen** [comment]
Thanks guys!

**Comment by gregwebs** [comment]
Can we get this released onto Hackage, or does it need more testing?

**Comment by TonyGen** [comment]
Hi Greg, I'm going to make a release tomorrow. Cheers.

**Comment by TonyGen** [comment]
A user found a bug in monad-control, so I'm postponing releasing this until it is fixed. See https://github.com/basvandijk/lifted-base/issues/1

**Comment by gregwebs** [comment]
is this issue present in monad-control 0.2 also? BTW, we have code like the following:

```
#if MIN_VERSION_monad_control(0, 3, 0)
import Control.Monad.Trans.Control (MonadBaseControl)
#define MBCIO MonadBaseControl IO
#else
import Control.Monad.IO.Control (MonadControlIO)
#define MBCIO MonadControlIO
#endif
```

**Comment by TonyGen** [comment]
Yes, this issue is also present in monad_control 0.2 and thus current mongoDB

**Comment by gregwebs** [comment]
So it doesn't seem that there is reason to put releasing a new driver with monad-control-0.3 on hold. Looks like you are going to solve your issue soon anyways though.

**Comment by TonyGen** [comment]
If Bas doesn't update monad-control in a week or so with his getValue fix. I will make my covert channel fix to my local generalized MVar and make a new release of mongoDB.

**Comment by snoyberg** [comment]
What's the status of this? I see the issue is closed, but the code on Hackage still requires 0.2.*. I ask because we're getting issues filed in Yesod about this, and I'd like to be able to test mongoDB with the upcoming release. As it stands now, we've completely removed mongoDB from our build scripts.

**Comment by scan** [comment]
I'd really like to know myself, because without this little bump I can't start my project.

**Comment by TonyGen** [comment]
Hi guys, When lifted-base is released with fix from https://github.com/basvandijk/lifted-base/issues/1, I will release mongoDB. Cheers.

**Comment by TonyGen** [comment]
I just release a new version of mongoDB using monad-control 0.3 and latest lifted-base fix.

**Comment by scan** [comment]
Thank you.

**Pull request merged**
